apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-sync-mini-store
  namespace: test
spec:
  schedule: "*/5 * * * *"   # toutes les 5 min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auto-sync
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              apk add --no-cache curl jq bash
              bash /scripts/check-and-update.sh
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          volumes:
          - name: scripts
            configMap:
              name: auto-sync-script
          restartPolicy: OnFailure