apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "store_admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "store_pass"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017