apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:7.0
          command:
            - mongos
            - --configdb
            - cfgReplSet/mongo-cfg-0.mongo-cfg-svc.dev.svc.cluster.local:27019,mongo-cfg-1.mongo-cfg-svc.dev.svc.cluster.local:27019,mongo-cfg-2.mongo-cfg-svc.dev.svc.cluster.local:27019
            - --bind_ip_all
            - --port
            - "27018"
          ports:
            - containerPort: 27018
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongos-svc
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 27018
      targetPort: 27018
      name: mongos
  selector:
    app: mongos