apiVersion: v1
kind: Service
metadata:
  name: mongos-service
  namespace: dev
spec:
  selector:
    app: mongos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
