apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:7.0
        command:
          - mongos
          - "--configdb"
          - "cfgReplSet/mongo-cfg-0.mongo-cfg-svc.dev.svc.cluster.local:27019,mongo-cfg-1.mongo-cfg-svc.dev.svc.cluster.local:27019,mongo-cfg-2.mongo-cfg-svc.dev.svc.cluster.local:27019"
          - "--bind_ip_all"
          - "--port"
          - "27017"
        ports:
        - containerPort: 27017
      imagePullSecrets:
      - name: docker-secret
